info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    id: 1231
    name: msoclientes
    response: msoclientes
    version: '@project.version@'

data:
  clientes: clientes.json
      
server:
  servlet:
    context-path: /msoclientes/v1
  port: 10500
